/**
 * The committed sample report shown at /demo.
 *
 * That page is the conversion surface — it is what a visitor sees before
 * deciding whether the paid tier is worth anything — and it is a *committed
 * artifact* regenerated by hand via scripts/build-sample.mjs. Nothing forces
 * that regeneration to happen when the checks change, so it can silently
 * advertise output the product no longer produces.
 *
 * Byte equality would be the obvious guard but the generators stamp today's
 * date, so it would fail a day after it was written. These assertions target
 * the drift that actually matters instead: findings the checks can no longer
 * emit, categories that no longer exist, and a result shape that has moved on.
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';

import { SAMPLE_RESULT } from '../src/worker/sample.js';
import { auditUrl } from '../src/core/audit.js';
import { CATEGORIES, SEVERITY_ORDER, runChecks } from '../src/core/checks.js';
import { AI_CRAWLERS } from '../src/core/robots.js';

/** Every finding id the current checks are capable of emitting. */
function producibleIds() {
  const ids = new Set();
  const pages = [
    '',
    '<html lang="en"><head><title>A title long enough</title></head><body><h1>H</h1><p>words words words</p></body></html>',
    '<html><head><title>App</title></head><body><div id="root"></div><script>var a=1;</script></body></html>',
  ];
  const companions = [
    {},
    {
      robots: { found: true, body: 'User-agent: *\nAllow: /\n', status: 200, url: 'r' },
      sitemap: { found: true, body: '<urlset></urlset>', status: 200, url: 's' },
      llms: { found: true, body: '# S\n\n> x\n\n- [a](https://a.test/a): a\n- [b](https://a.test/b): b\n- [c](https://a.test/c): c\n', status: 200, url: 'l' },
    },
    {
      robots: { found: true, body: 'User-agent: GPTBot\nDisallow: /\n\nUser-agent: *\nAllow: /\n', status: 200, url: 'r' },
      sitemap: { found: false, body: '', status: 404, url: 's' },
      llms: { found: false, body: '', status: 404, url: 'l' },
    },
  ];

  for (const body of pages) {
    for (const extra of companions) {
      const { findings } = runChecks({
        url: 'https://a.test/',
        page: {
          status: 200, ok: true, headers: { 'content-type': 'text/html; charset=utf-8' },
          body, bytes: body.length, elapsedMs: 5, redirects: [], truncated: false, finalUrl: 'https://a.test/',
        },
        ...extra,
      });
      for (const item of findings) ids.add(item.id);
    }
  }
  return ids;
}

test('the sample has the same shape as a fresh audit result', async () => {
  const server = http.createServer((req, res) => {
    res.writeHead(200, { 'content-type': 'text/html; charset=utf-8' });
    res.end('<html lang="en"><head><title>A title</title></head><body><h1>H</h1><p>hello</p></body></html>');
  });
  await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve));
  const fresh = await auditUrl(`http://127.0.0.1:${server.address().port}/`, {
    tier: 'pro',
    fetchOptions: { allowPrivate: true },
  });
  server.close();

  assert.deepEqual(
    Object.keys(SAMPLE_RESULT).sort(),
    Object.keys(fresh).sort(),
    'sample is stale — re-run `node scripts/build-sample.mjs`',
  );
  assert.deepEqual(Object.keys(SAMPLE_RESULT.generated).sort(), Object.keys(fresh.generated).sort());
  assert.deepEqual(Object.keys(SAMPLE_RESULT.stats).sort(), Object.keys(fresh.stats).sort());
});

test('every finding in the sample is one the checks can still produce', () => {
  const producible = producibleIds();
  for (const issue of SAMPLE_RESULT.issues) {
    assert.ok(
      producible.has(issue.id),
      `sample shows finding "${issue.id}" which no check emits any more — re-run \`node scripts/build-sample.mjs\``,
    );
    assert.ok(SEVERITY_ORDER.includes(issue.severity), `unknown severity in sample: ${issue.severity}`);
    assert.ok(issue.title && issue.detail, `sample finding ${issue.id} is missing text`);
  }
  assert.ok(SAMPLE_RESULT.issues.length > 0, 'the demo needs findings to show');
});

test('the sample categories match the current scoring model', () => {
  assert.deepEqual(Object.keys(SAMPLE_RESULT.categories).sort(), Object.keys(CATEGORIES).sort());
  for (const [key, category] of Object.entries(SAMPLE_RESULT.categories)) {
    assert.equal(category.label, CATEGORIES[key].label, `label drift for ${key}`);
    assert.equal(category.max, CATEGORIES[key].weight, `weight drift for ${key}`);
  }
});

test('the sample crawler matrix matches the registry', () => {
  const known = new Set(AI_CRAWLERS.map((crawler) => crawler.token));
  for (const crawler of SAMPLE_RESULT.crawlers) {
    assert.ok(known.has(crawler.token), `sample references retired crawler ${crawler.token}`);
  }
  assert.equal(SAMPLE_RESULT.crawlers.length, AI_CRAWLERS.length, 'sample predates a crawler registry change');
});

test('the demo shows the paid tier, since that is what it is selling', () => {
  assert.equal(SAMPLE_RESULT.tier, 'pro');
  assert.equal(SAMPLE_RESULT.issuesWithheld, 0);
  assert.ok(SAMPLE_RESULT.generated.robotsTxt.includes('User-agent:'));
  assert.ok(SAMPLE_RESULT.generated.llmsTxt.startsWith('# '));
  // A visitor should see a page with real problems — a clean demo sells nothing.
  assert.ok(SAMPLE_RESULT.issues.some((issue) => issue.severity === 'critical' || issue.severity === 'high'));
});

test('the sample leaks no build-time fixture details', () => {
  const serialised = JSON.stringify(SAMPLE_RESULT);
  assert.doesNotMatch(serialised, /127\.0\.0\.1|localhost/, 'fixture host leaked into the public demo');
  assert.match(SAMPLE_RESULT.url, /^https:\/\//);
});

test('the sample score is consistent with its own category totals', () => {
  const summed = Object.values(SAMPLE_RESULT.categories).reduce((total, category) => total + category.earned, 0);
  assert.ok(
    Math.abs(Math.round(summed) - SAMPLE_RESULT.score) <= 1,
    `sample score ${SAMPLE_RESULT.score} does not match its categories (${summed})`,
  );
});

test('the committed demo matches what the generator produces today', async (t) => {
  // The demo on the live site is committed output. If the checks change and
  // nobody reruns the builder, the shop window shows a report the product can
  // no longer produce — and there is no signal, because the file still parses
  // and still renders.
  //
  // The rebuild goes to a temporary file. It used to overwrite the committed
  // one and restore it in a `finally`, which is correct in isolation and wrong
  // in a suite: `node --test` runs test files in parallel processes, and
  // test/site-build.test.js spawns a build that imports src/worker/sample.js.
  // Landing inside the write window gave that build a parse error and exit 1,
  // so an unrelated test failed a few runs in a hundred with no clue why. A
  // suite that reddens at random is worse than no suite, because the habit it
  // teaches is to re-run rather than to look.
  const { execFile } = await import('node:child_process');
  const { mkdtemp, readFile, rm } = await import('node:fs/promises');
  const { fileURLToPath } = await import('node:url');
  const os = await import('node:os');
  const path = await import('node:path');

  const root = fileURLToPath(new URL('..', import.meta.url));
  const dir = await mkdtemp(path.join(os.tmpdir(), 'citable-sample-'));
  t.after(() => rm(dir, { recursive: true, force: true }));
  const rebuiltPath = path.join(dir, 'sample.js');

  await new Promise((resolve, reject) => {
    execFile(process.execPath, ['scripts/build-sample.mjs', rebuiltPath], { cwd: root }, (error) =>
      error ? reject(error) : resolve(),
    );
  });

  assert.equal(
    await readFile(rebuiltPath, 'utf8'),
    await readFile(new URL('../src/worker/sample.js', import.meta.url), 'utf8'),
    'src/worker/sample.js is out of date — run `node scripts/build-sample.mjs` and commit the result',
  );
});
