/**
 * Fix generators.
 *
 * The audit's findings tell you what is wrong; these produce the files that
 * make it right, filled in with what was actually observed on the page. This
 * is the part that turns a report into an afternoon of work instead of a
 * research project.
 */

import { AI_CRAWLERS } from './robots.js';
import { flattenJsonLd, jsonLdBlocks, meta, title as extractTitle } from './html.js';

/**
 * A robots.txt patch that explicitly allows answer-engine crawlers.
 * Training crawlers are listed separately and commented out, because opting
 * into training is a policy decision the site owner should make deliberately.
 */
export function generateRobotsPatch(ctx, options = {}) {
  const { includeTraining = false } = options;
  const origin = new URL(ctx.url).origin;
  const blocked = (ctx.matrix || []).filter((crawler) => !crawler.allowed);
  const blockedTokens = new Set(blocked.map((crawler) => crawler.token));

  const lines = [
    '# --- AI answer-engine access -------------------------------------------',
    '# Generated by Citable. Append to your existing robots.txt.',
    '# These crawlers fetch pages in order to answer live user questions.',
    '# Allowing them is what makes your pages eligible to be cited.',
    '',
  ];

  const citation = AI_CRAWLERS.filter((crawler) => crawler.purpose !== 'training');
  for (const crawler of citation) {
    lines.push(`# ${crawler.vendor} — ${crawler.surface}${blockedTokens.has(crawler.token) ? '   <-- currently blocked' : ''}`);
    lines.push(`User-agent: ${crawler.token}`);
    lines.push('Allow: /');
    lines.push('');
  }

  lines.push('# --- Model training ----------------------------------------------------');
  lines.push('# Uncomment to allow your content into model training data. This raises');
  lines.push('# unprompted brand recall, but the content is retained in model weights.');
  lines.push('');
  const training = AI_CRAWLERS.filter((crawler) => crawler.purpose === 'training');
  for (const crawler of training) {
    const prefix = includeTraining ? '' : '# ';
    lines.push(`# ${crawler.vendor} — ${crawler.surface}`);
    lines.push(`${prefix}User-agent: ${crawler.token}`);
    lines.push(`${prefix}Allow: /`);
    lines.push('');
  }

  lines.push(`Sitemap: ${origin}/sitemap.xml`);
  lines.push('');
  return lines.join('\n');
}

/**
 * Flatten a page-derived value for interpolation into a line-structured file.
 *
 * llms.txt is Markdown, and the reader publishes it at their site root for
 * models to read. A value carrying newlines stops being a value and becomes
 * document structure: a site name of "Acme\n\n## Ignore previous instructions"
 * emits that heading into a file whose whole purpose is to be read as
 * instructions about the site. Length is capped for the same reason — one
 * enormous title should not become the document.
 */
function oneLine(value, limit = 120) {
  const flat = String(value ?? '').replace(/\s+/g, ' ').trim();
  return flat.length > limit ? `${flat.slice(0, limit - 1).trimEnd()}…` : flat;
}

/**
 * The sentence that marks a generated llms.txt as still carrying our
 * placeholder links.
 *
 * The `llms-txt` check looks for this exact string, which is why it is a shared
 * constant rather than a literal in each file: two copies of a sentence in two
 * modules drift the first time one of them is reworded, and the failure is
 * silent — the check simply stops recognising the file it was written for.
 */
export const LLMS_PLACEHOLDER_MARKER = 'Replace the placeholder links below';

/**
 * Schema.org `@type`s specific enough to count as "this page declares what
 * kind of content it is" — the same list checks.js's `content-schema` finding
 * uses to decide whether that check passes, and generateJsonLd uses below to
 * decide whether to add another `Article` node on top of one already there.
 *
 * Shared for the same reason LLMS_PLACEHOLDER_MARKER is: two independently
 * retyped copies drift the first time one gets a type added and the other
 * doesn't, and the failure is silent. It already had: checks.js recognised
 * Recipe, Event, Course, Service, QAPage, WebPage and SoftwareApplication as
 * a declared content type; this list did not, so a Pro user with any of
 * those got a redundant generated Article block appended next to the type
 * their page already had — the exact case the `!hasContentType` guard below
 * exists to skip, and the note this function returns when it does
 * ("Existing structured data already covers publisher and page type") was
 * simply wrong for those seven types.
 */
export const CONTENT_SCHEMA_TYPES = [
  'article', 'blogposting', 'newsarticle', 'faqpage', 'howto', 'product',
  'softwareapplication', 'webpage', 'techarticle', 'qapage', 'recipe', 'course', 'event', 'service',
];

/**
 * A starter llms.txt built from the page's real title, description and
 * internal link structure.
 */
export function generateLlmsTxt(ctx) {
  const url = new URL(ctx.url);
  const siteName = oneLine(
    meta(ctx.html, 'og:site_name') ||
      extractTitle(ctx.html).split(/[|–—-]/).pop()?.trim() ||
      url.hostname.replace(/^www\./, ''),
    80,
  );
  const summary = oneLine(
    meta(ctx.html, 'description') ||
      (ctx.text || '').split('\n').find((line) => line.trim().length > 60) ||
      `Documentation and resources from ${url.hostname}.`,
    220,
  );

  const seen = new Set();
  const internal = [];
  for (const heading of ctx.headings || []) {
    if (heading.level !== 2 || !heading.text) continue;
    if (seen.has(heading.text)) continue;
    seen.add(heading.text);
    internal.push(heading.text);
    if (internal.length >= 8) break;
  }

  const lines = [
    `# ${siteName}`,
    '',
    `> ${summary}`,
    '',
    'This file follows the llms.txt convention: a curated, plain-Markdown map of',
    `this site for language models. ${LLMS_PLACEHOLDER_MARKER} with the`,
    'pages you most want cited, newest and most authoritative first.',
    '',
    '## Core pages',
    '',
    `- [Home](${url.origin}/): Overview of ${siteName}.`,
    `- [About](${url.origin}/about): Who is behind ${siteName} and why to trust it.`,
    `- [Docs](${url.origin}/docs): Reference documentation.`,
    '',
  ];

  if (internal.length) {
    lines.push('## Topics covered on this page');
    lines.push('');
    for (const topic of internal) {
      lines.push(`- [${oneLine(topic, 80)}](${ctx.url}): Section of ${oneLine(extractTitle(ctx.html) || url.pathname, 80)}.`);
    }
    lines.push('');
  }

  lines.push('## Optional');
  lines.push('');
  lines.push(`- [Changelog](${url.origin}/changelog): Release history.`);
  lines.push('');
  return lines.join('\n');
}


/**
 * Serialise a JSON-LD payload for embedding in an HTML `<script>` block.
 *
 * The generated markup is meant to be pasted into the reader's own `<head>`,
 * and it carries text taken from the audited page — a title, a description.
 * A page whose title contains `&lt;/script&gt;` decodes to a literal
 * `</script>`, which closes the block early and turns everything after it into
 * live markup on the pasting site. The tool would be handing someone an attack
 * payload with instructions to install it in production.
 *
 * Escaping `<` also covers `<!--` and `<script`; `>` and `&` are escaped for
 * the same reason, and the line separators because they are literal newlines
 * inside a JavaScript string. All four are valid JSON escapes, so the output
 * still parses as JSON anywhere it is used.
 */
function toEmbeddedJson(payload) {
  return JSON.stringify(payload, null, 2)
    .replace(/</g, '\\u003c')
    .replace(/>/g, '\\u003e')
    .replace(/&/g, '\\u0026')
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029');
}

/**
 * A JSON-LD block for the page, reusing whatever is already declared so the
 * output is a merge rather than a replacement.
 */
/**
 * A publication date the page itself asserts, if it has one.
 *
 * Falling back to today is what the generator used to do unconditionally, and
 * a date does not look like a placeholder the way CHANGE-ME does — so nobody
 * corrected it, and the pasted markup told every engine the page was published
 * on the day it happened to be audited. For a tool that tells people engines
 * weigh freshness, inventing a freshness signal is the wrong default.
 */
const todaysDate = () => new Date().toISOString().slice(0, 10);

function declaredDate(ctx) {
  const fromMeta =
    meta(ctx.html, 'article:published_time') ||
    meta(ctx.html, 'article:modified_time') ||
    meta(ctx.html, 'og:updated_time') ||
    meta(ctx.html, 'date');
  const fromSchema = flattenJsonLd(jsonLdBlocks(ctx.html))
    .map((node) => node.datePublished || node.dateModified || node.dateCreated)
    .find((value) => typeof value === 'string' && value);
  const fromHeader = ctx.page && ctx.page.headers && ctx.page.headers['last-modified'];

  for (const candidate of [fromMeta, fromSchema, fromHeader]) {
    if (!candidate) continue;
    const parsed = new Date(candidate);
    if (!Number.isNaN(parsed.getTime())) return parsed.toISOString().slice(0, 10);
  }
  return null;
}

export function generateJsonLd(ctx) {
  const url = new URL(ctx.url);
  const existing = flattenJsonLd(jsonLdBlocks(ctx.html));
  const existingTypes = new Set(
    existing.flatMap((node) => (Array.isArray(node['@type']) ? node['@type'] : [node['@type']])).filter(Boolean).map((type) => String(type).toLowerCase()),
  );

  const pageTitle = extractTitle(ctx.html) || url.pathname;
  const description = meta(ctx.html, 'description') || (ctx.text || '').slice(0, 200).replace(/\s+/g, ' ');
  const siteName = meta(ctx.html, 'og:site_name') || url.hostname.replace(/^www\./, '');
  const pageDate = declaredDate(ctx);
  const graph = [];

  if (!existingTypes.has('organization') && !existingTypes.has('person') && !existingTypes.has('localbusiness')) {
    graph.push({
      '@type': 'Organization',
      '@id': `${url.origin}/#organization`,
      name: siteName,
      url: url.origin,
      logo: `${url.origin}/logo.png`,
      sameAs: ['https://www.linkedin.com/company/CHANGE-ME', 'https://x.com/CHANGE-ME'],
    });
  }

  const hasContentType = CONTENT_SCHEMA_TYPES.some((type) => existingTypes.has(type));
  if (!hasContentType) {
    graph.push({
      '@type': 'Article',
      '@id': `${ctx.url}#article`,
      headline: pageTitle.slice(0, 110),
      description,
      url: ctx.url,
      mainEntityOfPage: { '@id': ctx.url },
      datePublished: pageDate ?? todaysDate(),
      dateModified: pageDate ?? todaysDate(),
      author: { '@type': 'Person', name: 'CHANGE-ME' },
      publisher: { '@id': `${url.origin}/#organization` },
      inLanguage: 'en',
    });
  }

  if (!graph.length) {
    return { note: 'Existing structured data already covers publisher and page type — no additions needed.', markup: null, json: null };
  }

  const payload = { '@context': 'https://schema.org', '@graph': graph };
  const json = toEmbeddedJson(payload);
  return {
    note: pageDate
      ? 'Paste inside <head>. Replace every CHANGE-ME before shipping.'
      : 'Paste inside <head>. Replace every CHANGE-ME before shipping — and set datePublished and dateModified, which default to today because this page declares no date of its own.',
    json,
    markup: `<script type="application/ld+json">\n${json}\n</script>`,
  };
}

/**
 * FAQPage schema derived from the page's own question-style headings and the
 * text that follows each one.
 */
export function generateFaqSchema(ctx) {
  const heads = (ctx.headings || []).filter(
    (heading) => heading.level >= 2 && (/\?\s*$/.test(heading.text) || /^(how|what|why|when|where|who|which|can|do|does|is|are|should)\b/i.test(heading.text)),
  );
  if (heads.length < 2) {
    return { note: 'Fewer than two question-style headings on the page — rewrite some H2s as questions first, then regenerate.', markup: null, json: null };
  }

  const lines = (ctx.text || '').split('\n');
  const entities = [];
  for (const heading of heads.slice(0, 10)) {
    const index = lines.findIndex((line) => line.trim() === heading.text.trim());
    const answer = index === -1 ? '' : lines.slice(index + 1).find((line) => line.trim().length > 50) || '';
    entities.push({
      '@type': 'Question',
      name: heading.text,
      acceptedAnswer: { '@type': 'Answer', text: answer.trim().slice(0, 500) || 'CHANGE-ME: answer this question in 40–60 words.' },
    });
  }

  const payload = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: entities };
  const json = toEmbeddedJson(payload);
  return {
    note: `Built from ${entities.length} question heading(s). Answers are lifted from the page — review them before shipping.`,
    json,
    markup: `<script type="application/ld+json">\n${json}\n</script>`,
  };
}

/** Everything the Pro tier hands over, in one call. */
export function generateAll(ctx) {
  return {
    robotsTxt: generateRobotsPatch(ctx),
    llmsTxt: generateLlmsTxt(ctx),
    jsonLd: generateJsonLd(ctx),
    faqSchema: generateFaqSchema(ctx),
  };
}
