/**
 * Report rendering.
 *
 * The Markdown report is a deliverable in its own right — it is the artifact an
 * agency hands a client, so it leads with the verdict and the money question
 * ("which engines can cite this page today"), then the fixes in the order they
 * should be done.
 */

const SEVERITY_LABEL = {
  critical: 'CRITICAL',
  high: 'HIGH',
  medium: 'MEDIUM',
  low: 'LOW',
  pass: 'PASS',
};

const BAR_WIDTH = 24;

function bar(ratio) {
  const filled = Math.round(Math.max(0, Math.min(1, ratio)) * BAR_WIDTH);
  return `${'█'.repeat(filled)}${'░'.repeat(BAR_WIDTH - filled)}`;
}

/** Full Markdown report for one page. */
export function renderMarkdown(result, options = {}) {
  const { brand = 'Citable', includeGenerated = true } = options;
  const lines = [];

  lines.push(`# AI Visibility Audit — ${result.url}`);
  lines.push('');
  lines.push(`**Score: ${result.score}/100 (${result.grade})** · ${result.verdict}`);
  lines.push('');
  lines.push(`Audited ${new Date(result.fetchedAt).toUTCString()} · HTTP ${result.http.status} in ${result.http.responseMs}ms · ${result.stats.words} words server-rendered`);
  lines.push('');

  lines.push('## Score breakdown');
  lines.push('');
  lines.push('| Category | Score | | What it measures |');
  lines.push('| --- | --- | --- | --- |');
  for (const category of Object.values(result.categories)) {
    lines.push(`| ${category.label} | ${category.earned}/${category.max} | \`${bar(category.ratio)}\` | ${category.blurb} |`);
  }
  lines.push('');

  if (result.crawlers && result.crawlers.length) {
    lines.push('## Which AI engines can reach this page');
    lines.push('');
    lines.push('| Crawler | Surface | Purpose | Status |');
    lines.push('| --- | --- | --- | --- |');
    for (const crawler of result.crawlers) {
      lines.push(
        `| \`${crawler.token}\` | ${crawler.surface} | ${crawler.purpose} | ${crawler.allowed ? 'Allowed' : `**Blocked** (${crawler.rule || 'group default'})`} |`,
      );
    }
    lines.push('');
  }

  lines.push(`## Findings (${result.issuesTotal} open)`);
  lines.push('');
  if (!result.issues.length) {
    lines.push('No open issues. Every check passed.');
    lines.push('');
  }
  result.issues.forEach((issue, index) => {
    lines.push(`### ${index + 1}. [${SEVERITY_LABEL[issue.severity]}] ${issue.title}`);
    lines.push('');
    lines.push(issue.detail);
    lines.push('');
    if (issue.evidence) {
      lines.push('```');
      lines.push(String(issue.evidence).slice(0, 1200));
      lines.push('```');
      lines.push('');
    }
    if (issue.impact) {
      lines.push(`**Costs you:** ${issue.impact}`);
      lines.push('');
    }
    if (issue.fix) {
      lines.push(`**Fix:** ${issue.fix}`);
      lines.push('');
    }
    lines.push(`*Recovers up to ${Math.round((issue.max - issue.earned) * 10) / 10} points.*`);
    lines.push('');
  });

  if (result.issuesWithheld > 0) {
    lines.push(`> ${result.issuesWithheld} further finding(s) and all generated fix files are included in ${brand} Pro.`);
    lines.push('');
  }

  if (result.passes && result.passes.length) {
    lines.push('## Already correct');
    lines.push('');
    for (const item of result.passes) lines.push(`- **${item.title}** — ${item.detail}`);
    lines.push('');
  }

  if (includeGenerated && result.generated) {
    lines.push('## Ready-to-ship fixes');
    lines.push('');

    lines.push('### robots.txt — append this');
    lines.push('');
    lines.push('```');
    lines.push(result.generated.robotsTxt.trim());
    lines.push('```');
    lines.push('');

    lines.push('### /llms.txt — create this file');
    lines.push('');
    lines.push('```markdown');
    lines.push(result.generated.llmsTxt.trim());
    lines.push('```');
    lines.push('');

    lines.push('### JSON-LD — paste inside `<head>`');
    lines.push('');
    lines.push(result.generated.jsonLd.note);
    lines.push('');
    if (result.generated.jsonLd.markup) {
      lines.push('```html');
      lines.push(result.generated.jsonLd.markup);
      lines.push('```');
      lines.push('');
    }

    lines.push('### FAQPage schema');
    lines.push('');
    lines.push(result.generated.faqSchema.note);
    lines.push('');
    if (result.generated.faqSchema.markup) {
      lines.push('```html');
      lines.push(result.generated.faqSchema.markup);
      lines.push('```');
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('');
  lines.push(`Generated by ${brand}.`);
  lines.push('');
  return lines.join('\n');
}

/** Site-level rollup across many pages. */
export function renderSiteMarkdown(rollup, options = {}) {
  const { brand = 'Citable' } = options;
  const lines = [];

  lines.push('# Site-wide AI Visibility Audit');
  lines.push('');
  lines.push(`**Average score: ${rollup.averageScore}/100** across ${rollup.pagesAudited} page(s)${rollup.pagesFailed ? ` (${rollup.pagesFailed} failed to fetch)` : ''}.`);
  lines.push('');

  if (rollup.sitewideIssues.length) {
    lines.push('## Template-level issues');
    lines.push('');
    lines.push('Issues appearing on many pages usually live in a shared template, so one fix moves every page at once. Do these first.');
    lines.push('');
    lines.push('| Issue | Severity | Pages affected | Fix |');
    lines.push('| --- | --- | --- | --- |');
    for (const issue of rollup.sitewideIssues) {
      lines.push(`| ${issue.title} | ${SEVERITY_LABEL[issue.severity]} | ${issue.pages} | ${issue.fix || '—'} |`);
    }
    lines.push('');
  }

  lines.push('## Pages');
  lines.push('');
  lines.push('| Page | Score | Open issues |');
  lines.push('| --- | --- | --- |');
  for (const page of rollup.pages) {
    if (typeof page.score !== 'number') {
      lines.push(`| ${page.url} | — | fetch failed: ${page.error} |`);
      continue;
    }
    lines.push(`| ${page.url} | ${page.score}/100 (${page.grade}) | ${page.issuesTotal} |`);
  }
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(`Generated by ${brand}.`);
  lines.push('');
  return lines.join('\n');
}

/* --------------------------------------------------------------- terminal */

const ANSI = {
  reset: '[0m',
  bold: '[1m',
  dim: '[2m',
  red: '[31m',
  yellow: '[33m',
  green: '[32m',
  cyan: '[36m',
  grey: '[90m',
};

const SEVERITY_COLOR = {
  critical: ANSI.red,
  high: ANSI.red,
  medium: ANSI.yellow,
  low: ANSI.cyan,
  pass: ANSI.green,
};

/** Coloured terminal output for the CLI. */
export function renderTerminal(result, options = {}) {
  const { color = true, verbose = false } = options;
  const paint = (code, text) => (color ? `${code}${text}${ANSI.reset}` : text);
  const lines = [];

  const scoreColor = result.score >= 80 ? ANSI.green : result.score >= 60 ? ANSI.yellow : ANSI.red;
  lines.push('');
  lines.push(paint(ANSI.bold, result.url));
  lines.push(`${paint(scoreColor, `${result.score}/100`)} ${paint(ANSI.dim, `(${result.grade})`)}  ${result.verdict}`);
  lines.push('');

  for (const category of Object.values(result.categories)) {
    const label = category.label.padEnd(18);
    const ratioColor = category.ratio >= 0.8 ? ANSI.green : category.ratio >= 0.5 ? ANSI.yellow : ANSI.red;
    lines.push(`  ${label} ${paint(ratioColor, bar(category.ratio))} ${String(category.earned).padStart(4)}/${category.max}`);
  }
  lines.push('');

  const blocked = (result.crawlers || []).filter((crawler) => !crawler.allowed);
  if (blocked.length) {
    lines.push(paint(ANSI.red, `  Blocked crawlers: ${blocked.map((crawler) => crawler.token).join(', ')}`));
    lines.push('');
  }

  if (result.issues.length) {
    lines.push(paint(ANSI.bold, `Findings (${result.issuesTotal} open)`));
    lines.push('');
    result.issues.forEach((issue, index) => {
      const tag = paint(SEVERITY_COLOR[issue.severity] || '', `[${SEVERITY_LABEL[issue.severity]}]`);
      lines.push(`  ${index + 1}. ${tag} ${paint(ANSI.bold, issue.title)}`);
      lines.push(`     ${wrap(issue.detail, 92, '     ')}`);
      if (verbose && issue.evidence) {
        lines.push(paint(ANSI.grey, indent(String(issue.evidence).slice(0, 500), '       ')));
      }
      if (issue.fix) lines.push(`     ${paint(ANSI.cyan, '→ ')}${wrap(issue.fix, 92, '     ')}`);
      lines.push('');
    });
  } else {
    lines.push(paint(ANSI.green, '  No open issues.'));
    lines.push('');
  }

  if (result.issuesWithheld > 0) {
    lines.push(paint(ANSI.dim, `  ${result.issuesWithheld} more finding(s) + generated robots.txt / llms.txt / JSON-LD available with a Pro key.`));
    lines.push('');
  }

  return lines.join('\n');
}

function wrap(text, width, prefix) {
  const words = String(text || '').split(/\s+/);
  const out = [];
  let line = '';
  for (const word of words) {
    if (line.length + word.length + 1 > width) {
      out.push(line);
      line = word;
    } else {
      line = line ? `${line} ${word}` : word;
    }
  }
  if (line) out.push(line);
  return out.join(`\n${prefix}`);
}

function indent(text, prefix) {
  return String(text)
    .split('\n')
    .map((line) => `${prefix}${line}`)
    .join('\n');
}
